export const OBJECTIVE_ANSWER_KEYS = {
  "ielts1": {
    "listening": {
      "1": "9.30 (am) / 9:30 (am) / 9 30 (am) / 9.30 (AM) / 9:30 (AM) / 9 30 (AM)",
      "2": "Helendale",
      "3": "Central Street/ Central St",
      "4": "(number/no./#) 792",
      "5": "8.55 (am) / 8:55 (am) / 8.55 (AM) / 8:55 (AM)",
      "6": "1.80",
      "7": "7.30/7:30",
      "8": "7.15",
      "9": "commuter",
      "10": "afternoon",
      "11": "a",
      "12": "c",
      "13": "b",
      "14": "c",
      "15": "first year/1st year/ First year",
      "16": "(right) balance",
      "17": "international (students) / foreign (students)",
      "18": "relaxation/Relaxation",
      "19": "motivation/Motivation",
      "20": "research/advanced/Research/Advanced",
      "21": "The Secret Garden",
      "22": "(the) 20th century/twentieth century",
      "23": "walk",
      "24": "motivations/motivation",
      "25": "abstract ideas",
      "26": "roses",
      "27": "dark to light / darkness to lightness",
      "28": "health/Health",
      "29": "environment/Environment",
      "30": "human companionship",
      "31": "negative/Negative",
      "32": "pleasure",
      "33": "poverty",
      "34": "active/Active",
      "35": "success",
      "36": "b",
      "37": "a",
      "38": "c",
      "39": "a",
      "40": "b"
    },
    "reading": {
      "1": "vi",
      "2": "viii",
      "3": "vii",
      "4": "i",
      "5": "ii",
      "6": "iv",
      "7": "Royal Society / royal society",
      "8": "(his) niece / His niece / Niece",
      "9": "telescope",
      "10": "optics",
      "11": "particles",
      "12": "motion",
      "13": "calculus",
      "14": "remote",
      "15": "native population",
      "16": "single",
      "17": "Ice shelves / ice shelves",
      "18": "not given",
      "19": "FALSE",
      "20": "TRUE",
      "21": "FALSE",
      "22": "E",
      "23": "C",
      "24": "A",
      "25": "G",
      "26": "D",
      "27": "D",
      "28": "B",
      "29": "A",
      "30": "B",
      "31": "B",
      "32": "not given",
      "33": "TRUE / yes",
      "34": "false / no",
      "35": "not given",
      "36": "false / no",
      "37": "D",
      "38": "C",
      "39": "A",
      "40": "B"
    }
  },
  "ielts2": {
    "listening": {
      "1": "Lynda",
      "2": "Unit 15 / Unit fifteen",
      "3": "5577",
      "4": "night shift",
      "5": "swipe card",
      "6": "September 1975 / Sept 1975",
      "7": "A / C",
      "8": "A / C",
      "9": "Fifteen dollars / fifteen dollars / $15 / 15 dollars",
      "10": "60 minutes/sixty minutes/one hour/1 hour",
      "11": "B",
      "12": "A",
      "13": "A",
      "14": "B",
      "15": "C",
      "16": "2 July/2nd July",
      "17": "9:15 AM/9:15 am/9.15/9:15/nine fifteen AM/nine fifteen am/9:15 A.M./9:15 a.m./9.15/9:15/nine fifteen A.M./nine fifteen a.m.",
      "18": "president",
      "19": "Observation hut / observation hut",
      "20": "2 PM/2 pm/two pm/2 p.m/ 2 P.M.",
      "21": "safety procedures / directions / safety rules",
      "22": "eye protection / safety glasses / goggles",
      "23": "clean-up / clean up / cleanup",
      "24": "naked flame",
      "25": "leather",
      "26": "C",
      "27": "B",
      "28": "C",
      "29": "C/E",
      "30": "C/E",
      "31": "fuel",
      "32": "Combustion engine / combustion engine",
      "33": "145% / 145 per cent",
      "34": "agriculture",
      "35": "(a) barrier",
      "36": "46 million",
      "37": "118 million",
      "38": "vegetation zones",
      "39": "(certain) disease(s)",
      "40": "species composition"
    },
    "reading": {
      "1": "viii",
      "2": "iii",
      "3": "vii",
      "4": "i",
      "5": "vi",
      "6": "ix",
      "7": "ii",
      "8": "Cauliflower rosettes / cauliflower rosettes",
      "9": "Periodic unsettling / periodic unsettling",
      "10": "Milk sugars / milk sugars",
      "11": "Liquefied yogurt / liquefied yogurt",
      "12": "C/E",
      "13": "C/E",
      "14": "vi",
      "15": "ix",
      "16": "v",
      "17": "iv",
      "18": "x",
      "19": "ii",
      "20": "vii",
      "21": "iii",
      "22": "energy",
      "23": "subsistence needs",
      "24": "rural/impoverished",
      "25": "pesticide use",
      "26": "protein deficiency",
      "27": "D",
      "28": "E",
      "29": "A",
      "30": "C",
      "31": "B",
      "32": "E",
      "33": "B",
      "34": "F",
      "35": "true / yes",
      "36": "true / yes",
      "37": "true / yes",
      "38": "false / no",
      "39": "not given",
      "40": "false / no"
    }
  },
  "ielts3": {
    "listening": {
      "1": "documents",
      "2": "keyboard",
      "3": "flowers",
      "4": "tools",
      "5": "Saturday",
      "6": "Mairead",
      "7": "bridge",
      "8": "May 14 / 14 May / 14th May / May 14th",
      "9": "park",
      "10": "newspaper",
      "11": "C",
      "12": "B",
      "13": "A",
      "14": "H",
      "15": "G",
      "16": "films",
      "17": "reports",
      "18": "region",
      "19": "job",
      "20": "housing",
      "21": "E",
      "22": "I",
      "23": "C",
      "24": "G",
      "25": "B",
      "26": "D",
      "27": "A",
      "28": "aims / goals",
      "29": "staff",
      "30": "feedback",
      "31": "hook",
      "32": "string",
      "33": "danger",
      "34": "rubber",
      "35": "light",
      "36": "intelligence",
      "37": "tails",
      "38": "energy",
      "39": "chemical",
      "40": "diet"
    },
    "reading": {
      "1": "seafaring",
      "2": "merchant",
      "3": "temple",
      "4": "craftsmen",
      "5": "timber / wood",
      "6": "partnership",
      "7": "ivory",
      "8": "commission",
      "9": "TRUE",
      "10": "FALSE",
      "11": "TRUE",
      "12": "TRUE",
      "13": "not given",
      "14": "iv",
      "15": "ii",
      "16": "vii",
      "17": "i",
      "18": "v",
      "19": "vi",
      "20": "FALSE",
      "21": "TRUE",
      "22": "not given",
      "23": "TRUE",
      "24": "vertical integration",
      "25": "movie moguls",
      "26": "divestiture",
      "27": "D",
      "28": "C",
      "29": "E",
      "30": "B",
      "31": "environmental",
      "32": "light",
      "33": "multi-tasking / multitasking",
      "34": "food",
      "35": "predator",
      "36": "E",
      "37": "H",
      "38": "B",
      "39": "B",
      "40": "A"
    }
  },
  "ielts4": {
    "listening": {
      "1": "unfriendly",
      "2": "false / noisy",
      "3": "23.50 / 23:50",
      "4": "insects",
      "5": "bathrooms",
      "6": "party",
      "7": "Shadforth / shadforth",
      "8": "towel",
      "9": "breakfast",
      "10": "kitchen",
      "11": "B",
      "12": "A",
      "13": "C",
      "14": "B",
      "15": "A",
      "16": "A",
      "17": "E",
      "18": "C",
      "19": "F",
      "20": "A",
      "21": "A",
      "22": "B",
      "23": "A",
      "24": "B",
      "25": "A",
      "26": "A",
      "27": "background",
      "28": "theory",
      "29": "costs",
      "30": "time",
      "31": "religions",
      "32": "nature",
      "33": "flight",
      "34": "stars",
      "35": "practical",
      "36": "education",
      "37": "king",
      "38": "entertainment",
      "39": "opera",
      "40": "electricity"
    },
    "reading": {
      "1": "TRUE",
      "2": "FALSE",
      "3": "not given",
      "4": "not given",
      "5": "TRUE",
      "6": "FALSE",
      "7": "TRUE",
      "8": "D",
      "9": "B",
      "10": "G",
      "11": "C",
      "12": "E",
      "13": "F",
      "14": "hairs",
      "15": "charge / electric charge",
      "16": "pores",
      "17": "water",
      "18": "concave",
      "19": "E",
      "20": "D",
      "21": "B",
      "22": "C",
      "23": "E",
      "24": "I",
      "25": "F",
      "26": "H",
      "27": "i",
      "28": "x",
      "29": "ii",
      "30": "vii",
      "31": "iii",
      "32": "v",
      "33": "F",
      "34": "E",
      "35": "C",
      "36": "D",
      "37": "B",
      "38": "E",
      "39": "A",
      "40": "E"
    }
  },
  "ielts5": {
    "listening": {
      "1": "2086132978",
      "2": "visiontech",
      "3": "doctor",
      "4": "garage",
      "5": "furniture",
      "6": "fridge",
      "7": "school",
      "8": "950",
      "9": "quiet",
      "10": "friend",
      "11": "contact details",
      "12": "emergency",
      "13": "radio",
      "14": "extra keys / (extra) keys / spare keys",
      "15": "window locks / (window) locks",
      "16": "C",
      "17": "D",
      "18": "F",
      "19": "G",
      "20": "E",
      "21": "B",
      "22": "C",
      "23": "B",
      "24": "A",
      "25": "C",
      "26": "C",
      "27": "global hunger / hunger",
      "28": "pollution",
      "29": "wood",
      "30": "grass",
      "31": "marketing",
      "32": "interests",
      "33": "jobs",
      "34": "health",
      "35": "C",
      "36": "E",
      "37": "A",
      "38": "D",
      "39": "A",
      "40": "C"
    },
    "reading": {
      "1": "v / vi",
      "2": "viii / vii",
      "3": "i",
      "4": "vi / iv",
      "5": "iv / viii",
      "6": "ii",
      "7": "national development / science",
      "8": "economy",
      "9": "guidelines",
      "10": "memorisation / language",
      "11": "equipment",
      "12": "masters degree / master's degree",
      "13": "respect / status / social respect",
      "14": "ii / viii",
      "15": "iv / iii",
      "16": "vi / vii",
      "17": "iii / iv",
      "18": "vii / vi",
      "19": "viii / ix",
      "20": "i / ii",
      "21": "cauliflower rosettes",
      "22": "fermentation process / periodic unsettling",
      "23": "milk sugars",
      "24": "liquified yogurt / liquefied yogurt / yogurt",
      "25": "B / C",
      "26": "E",
      "27": "D",
      "28": "B",
      "29": "A",
      "30": "C",
      "31": "B",
      "32": "D / C",
      "33": "E / D",
      "34": "A",
      "35": "workplace / workplaces",
      "36": "conversations / acquaintances",
      "37": "behaviour / conversations",
      "38": "behaviour / internet",
      "39": "waste / cities",
      "40": "A"
    }
  },
  "ielts6": {
    "listening": {
      "1": "white",
      "2": "office",
      "3": "camera",
      "4": "umbrella",
      "5": "13 May / May 13 / May 13th / 13th May",
      "6": "airport",
      "7": "taxi",
      "8": "Docherty",
      "9": "River",
      "10": "07979605437",
      "11": "G",
      "12": "D",
      "13": "A",
      "14": "E",
      "15": "C",
      "16": "B",
      "17": "A",
      "18": "C",
      "19": "C",
      "20": "A",
      "21": "B",
      "22": "A",
      "23": "A",
      "24": "C",
      "25": "B",
      "26": "E",
      "27": "B",
      "28": "G",
      "29": "A",
      "30": "F",
      "31": "migration",
      "32": "eyes",
      "33": "lizard",
      "34": "trade",
      "35": "survival",
      "36": "political",
      "37": "ships",
      "38": "horses",
      "39": "industry",
      "40": "tourism"
    },
    "reading": {
      "1": "vi",
      "2": "x",
      "3": "iii",
      "4": "ix",
      "5": "iv",
      "6": "i",
      "7": "vii",
      "8": "north America",
      "9": "super hot fires / hot fires / fires",
      "10": "stored carbon / (stored) carbon",
      "11": "winds",
      "12": "drought",
      "13": "beetle",
      "14": "skin samples / skin (samples)",
      "15": "noise pollution / noise (pollution)",
      "16": "around Tasmania / (around) Tasmania",
      "17": "sperm whales / sperm (whales)",
      "18": "sound waves",
      "19": "nutrients",
      "20": "microbubbles",
      "21": "blood",
      "22": "not given",
      "23": "TRUE",
      "24": "not given",
      "25": "TRUE",
      "26": "FALSE",
      "27": "B",
      "28": "A",
      "29": "B",
      "30": "D",
      "31": "C",
      "32": "D",
      "33": "B",
      "34": "C",
      "35": "A",
      "36": "H",
      "37": "D",
      "38": "F",
      "39": "G",
      "40": "B"
    }
  },
  "ielts7": {
    "listening": {
      "1": "7.30 / 7:30",
      "2": "pencils",
      "3": "top",
      "4": "August",
      "5": "instructions",
      "6": "55",
      "7": "beginners",
      "8": "Kahui / kahui",
      "9": "battery",
      "10": "show",
      "11": "B",
      "12": "E",
      "13": "B",
      "14": "C",
      "15": "G",
      "16": "I",
      "17": "B",
      "18": "E",
      "19": "C",
      "20": "A",
      "21": "C",
      "22": "A",
      "23": "B",
      "24": "C",
      "25": "A",
      "26": "G",
      "27": "A",
      "28": "D",
      "29": "C",
      "30": "E",
      "31": "food",
      "32": "hero",
      "33": "feathers",
      "34": "shells",
      "35": "diamond",
      "36": "shark",
      "37": "teeth",
      "38": "messages",
      "39": "meeting",
      "40": "escape"
    },
    "reading": {
      "1": "FALSE",
      "2": "not given",
      "3": "TRUE",
      "4": "TRUE",
      "5": "not given",
      "6": "FALSE",
      "7": "not given",
      "8": "not given",
      "9": "A",
      "10": "B",
      "11": "C",
      "12": "C",
      "13": "A",
      "14": "not given",
      "15": "TRUE / yes",
      "16": "FALSE / no",
      "17": "not given",
      "18": "fertilizer / fertiliser",
      "19": "lasers",
      "20": "cereals",
      "21": "communication",
      "22": "C",
      "23": "F",
      "24": "H",
      "25": "A",
      "26": "D",
      "27": "E",
      "28": "D",
      "29": "C",
      "30": "E",
      "31": "A",
      "32": "B",
      "33": "C",
      "34": "D",
      "35": "B",
      "36": "C",
      "37": "generation",
      "38": "citizen",
      "39": "abstract",
      "40": "music"
    }
  },
  "ielts8": {
    "listening": {
      "1": "C",
      "2": "C",
      "3": "C",
      "4": "13th november / 13 november / november 13th / november 13",
      "5": "8.00 / 8 a.m. / eight / 8 / \t8.00 A.M.",
      "6": "15 / fifteen",
      "7": "£3.25",
      "8": "dairy-free / dairy free",
      "9": "Beecham",
      "10": "523",
      "11": "direct sunlight",
      "12": "energy usage",
      "13": "cool shower",
      "14": "cooling points",
      "15": "sweating",
      "16": "11 to 3 / 11 a.m. to 3 p.m. / eleven to three",
      "17": "umbrella",
      "18": "cotton or linen",
      "19": "physical exercise",
      "20": "health issues",
      "21": "C",
      "22": "C",
      "23": "B",
      "24": "A",
      "25": "C",
      "26": "well constructed",
      "27": "relevant",
      "28": "typing mistakes",
      "29": "sentence structures",
      "30": "punctuation",
      "31": "B",
      "32": "C",
      "33": "A",
      "34": "C",
      "35": "B",
      "36": "A",
      "37": "C",
      "38": "winter months",
      "39": "positive attitude",
      "40": "motivated"
    },
    "reading": {
      "1": "C",
      "2": "F",
      "3": "I",
      "4": "B",
      "5": "G",
      "6": "action",
      "7": "angle",
      "8": "re-form",
      "9": "undermined",
      "10": "crashing",
      "11": "absorbing",
      "12": "lifespan",
      "13": "D",
      "14": "B",
      "15": "hierarchy",
      "16": "emerge",
      "17": "cooperation",
      "18": "norms",
      "19": "performance",
      "20": "B",
      "21": "E",
      "22": "D",
      "23": "E",
      "24": "not given",
      "25": "TRUE",
      "26": "FALSE",
      "27": "not given",
      "28": "TRUE",
      "29": "TRUE",
      "30": "confusion",
      "31": "patterns",
      "32": "interpret",
      "33": "A",
      "34": "B",
      "35": "B",
      "36": "C",
      "37": "basis",
      "38": "fine-tunes",
      "39": "deletes",
      "40": "curation"
    }
  },
  "ielts9": {
    "listening": {
      "1": "Marrowfield",
      "2": "relative",
      "3": "socialise / socialize",
      "4": "full",
      "5": "Domestic Life",
      "6": "clouds",
      "7": "timing",
      "8": "Animal Magic",
      "9": "(animal) movement",
      "10": "dark",
      "11": "B / C",
      "12": "B / C",
      "13": "B / D",
      "14": "B / D",
      "15": "C",
      "16": "B",
      "17": "B",
      "18": "C",
      "19": "A",
      "20": "A",
      "21": "A / E",
      "22": "A / E",
      "23": "B / D",
      "24": "B / D",
      "25": "G",
      "26": "E",
      "27": "B",
      "28": "C",
      "29": "F",
      "30": "A",
      "31": "technical",
      "32": "cheap",
      "33": "thousands",
      "34": "identification",
      "35": "tracking",
      "36": "military",
      "37": "location",
      "38": "prediction",
      "39": "database",
      "40": "trust"
    },
    "reading": {
      "1": "G",
      "2": "D",
      "3": "C",
      "4": "F",
      "5": "architects",
      "6": "moisture",
      "7": "layers",
      "8": "speed",
      "9": "C",
      "10": "A",
      "11": "B",
      "12": "D",
      "13": "A",
      "14": "iii",
      "15": "viii",
      "16": "vi",
      "17": "v",
      "18": "vii",
      "19": "i",
      "20": "iv",
      "21": "A",
      "22": "C",
      "23": "B",
      "24": "speed",
      "25": "Fifty / 50",
      "26": "strict",
      "27": "B",
      "28": "A",
      "29": "C",
      "30": "C",
      "31": "H",
      "32": "D",
      "33": "F",
      "34": "E",
      "35": "B",
      "36": "false / no",
      "37": "not given",
      "38": "true / yes",
      "39": "false / no",
      "40": "not given"
    }
  },
  "ielts10": {
    "listening": {
      "1": "port",
      "2": "13th September / 13 September / September 13 / September 13th",
      "3": "1100",
      "4": "Beatrice ",
      "5": "07740922166",
      "6": "b.russell64@mail.co.uk",
      "7": "garden",
      "8": "1000",
      "9": "center / centre",
      "10": "parking",
      "11": "C",
      "12": "B",
      "13": "A",
      "14": "C",
      "15": "A",
      "16": "C",
      "17": "B",
      "18": "A",
      "19": "C",
      "20": "B",
      "21": "B / C",
      "22": "B / C",
      "23": "A / E",
      "24": "A / E",
      "25": "C / D",
      "26": "C / D",
      "27": "E",
      "28": "B",
      "29": "A",
      "30": "C",
      "31": "corporate",
      "32": "exploit",
      "33": "staff",
      "34": "shock",
      "35": "laws",
      "36": "year",
      "37": "marketing",
      "38": "charities",
      "39": "cheap",
      "40": "relevant"
    },
    "reading": {
      "1": "iii",
      "2": "i",
      "3": "vi",
      "4": "viii",
      "5": "v",
      "6": "2006",
      "7": "butterflies",
      "8": "hibernation",
      "9": "extinction / extinctions",
      "10": "TRUE",
      "11": "not given",
      "12": "FALSE",
      "13": "not given",
      "14": "C / E / F",
      "15": "C / E / F",
      "16": "C / E / F",
      "17": "B / C / G",
      "18": "B / C / G",
      "19": "B / C / G",
      "20": "CT",
      "21": "PA",
      "22": "OH",
      "23": "SP",
      "24": "HF",
      "25": "OH",
      "26": "D",
      "27": "(giant) clams",
      "28": "ten months",
      "29": "marble and bronze",
      "30": "wooden casing",
      "31": "inscriptions",
      "32": "(mechanical) clock",
      "33": "C",
      "34": "H",
      "35": "F",
      "36": "G",
      "37": "B",
      "38": "C",
      "39": "C",
      "40": "A"
    }
  },
  "ielts11": {
    "listening": {
      "1": "48",
      "2": "RI6 GH7 / RI6GH7",
      "3": "07754897432",
      "4": "PA 365 / PA365",
      "5": "E6",
      "6": "B / D / E",
      "7": "B / D / E",
      "8": "B / D / E",
      "9": "C",
      "10": "C",
      "11": "C",
      "12": "B",
      "13": "A",
      "14": "F",
      "15": "A / C",
      "16": "A / C",
      "17": "C / E",
      "18": "C / E",
      "19": "B / C",
      "20": "B / C",
      "21": "A",
      "22": "C",
      "23": "A",
      "24": "B",
      "25": "B",
      "26": "ten / 10",
      "27": "Africa / Asia",
      "28": "1000 / 1000 words",
      "29": "30th of October / 30 October / 30th October / October 30 / October 30th / 30.10",
      "30": "B",
      "31": "C",
      "32": "B",
      "33": "B",
      "34": "B",
      "35": "(very) calm seas",
      "36": "larger slicks",
      "37": "toxic waste",
      "38": "eco-friendly",
      "39": "(discernible) drawbacks",
      "40": "deadline for submission"
    },
    "reading": {
      "1": "viii",
      "2": "i",
      "3": "ix",
      "4": "vii",
      "5": "v",
      "6": "iii",
      "7": "false / no",
      "8": "true / yes",
      "9": "not given",
      "10": "not given",
      "11": "true / yes",
      "12": "not given",
      "13": "false / no",
      "14": "true / yes",
      "15": "C",
      "16": "F",
      "17": "H",
      "18": "G",
      "19": "B",
      "20": "C",
      "21": "D",
      "22": "B",
      "23": "C",
      "24": "A",
      "25": "not given",
      "26": "TRUE",
      "27": "TRUE",
      "28": "AP",
      "29": "RH",
      "30": "PJ",
      "31": "BB",
      "32": "TB",
      "33": "SB",
      "34": "PJ",
      "35": "PL",
      "36": "FALSE",
      "37": "TRUE",
      "38": "TRUE",
      "39": "TRUE",
      "40": "not given"
    }
  },
  "ielts12": {
    "listening": {
      "1": "missing",
      "2": "WS178GP",
      "3": "classic",
      "4": "PT9475",
      "5": "top",
      "6": "4.45 / 4:45",
      "7": "gcooper45",
      "8": "helpful",
      "9": "weight",
      "10": "small",
      "11": "A",
      "12": "E",
      "13": "D",
      "14": "B",
      "15": "B / D",
      "16": "B / D",
      "17": "C / E",
      "18": "C / E",
      "19": "A / C",
      "20": "A / C",
      "21": "A",
      "22": "B",
      "23": "B",
      "24": "C",
      "25": "30",
      "26": "drop out",
      "27": "engineering",
      "28": "teachers",
      "29": "significant",
      "30": "exams",
      "31": "university",
      "32": "lobby",
      "33": "wall",
      "34": "angles",
      "35": "sharp",
      "36": "thinner",
      "37": "sport",
      "38": "showrooms",
      "39": "energy",
      "40": "peaked"
    },
    "reading": {
      "1": "D",
      "2": "B",
      "3": "A",
      "4": "C",
      "5": "B",
      "6": "A",
      "7": "microblogging",
      "8": "abstract",
      "9": "upstroke",
      "10": "A / E",
      "11": "A / E",
      "12": "C / D",
      "13": "C / D",
      "14": "B",
      "15": "A",
      "16": "G",
      "17": "H",
      "18": "F",
      "19": "I",
      "20": "D",
      "21": "rounded",
      "22": "grains",
      "23": "(coastal) ecosystems",
      "24": "erosion",
      "25": "not given",
      "26": "false / no",
      "27": "true / yes",
      "28": "G",
      "29": "D",
      "30": "E",
      "31": "F",
      "32": "C",
      "33": "D",
      "34": "B",
      "35": "A",
      "36": "not given",
      "37": "true / yes",
      "38": "true / yes",
      "39": "not given",
      "40": "false / no"
    }
  },
  "ielts13": {
    "listening": {
      "1": "90",
      "2": "medical",
      "3": "birth",
      "4": "6 months",
      "5": "recent",
      "6": "British",
      "7": "Seymour",
      "8": "07822953007",
      "9": "1998",
      "10": "England",
      "11": "A / C",
      "12": "A / C",
      "13": "B / E",
      "14": "B / E",
      "15": "A / E",
      "16": "A / E",
      "17": "C",
      "18": "B",
      "19": "A",
      "20": "B",
      "21": "C",
      "22": "A",
      "23": "C",
      "24": "B",
      "25": "G",
      "26": "E",
      "27": "C",
      "28": "D",
      "29": "F",
      "30": "A",
      "31": "sensible",
      "32": "rules",
      "33": "emotional",
      "34": "conflict",
      "35": "strangers",
      "36": "socialize",
      "37": "cyclist",
      "38": "champion",
      "39": "depression",
      "40": "running"
    },
    "reading": {
      "1": "TRUE",
      "2": "TRUE",
      "3": "not given",
      "4": "TRUE",
      "5": "not given",
      "6": "FALSE",
      "7": "treatment",
      "8": "amygdala",
      "9": "diagnosis",
      "10": "the individual / employees",
      "11": "adverse effects",
      "12": "anxiety",
      "13": "understanding",
      "14": "ten minutes",
      "15": "exact measurements",
      "16": "astronomical observations / the sun",
      "17": "railroads / rail roads / railways",
      "18": "(diminutive) size",
      "19": "(safety) concerns",
      "20": "railway companies",
      "21": "C",
      "22": "D",
      "23": "B",
      "24": "A",
      "25": "A / D / E",
      "26": "A / D / E",
      "27": "A / D / E",
      "28": "bedrock",
      "29": "local community",
      "30": "storage capsules",
      "31": "thorns",
      "32": "nuclear waste",
      "33": "C",
      "34": "A",
      "35": "F",
      "36": "E",
      "37": "H",
      "38": "false / no",
      "39": "true / yes",
      "40": "not given"
    }
  },
  "ielts14": {
    "listening": {
      "1": "6 / six",
      "2": "magazine",
      "3": "90 minutes / 1.5 hours",
      "4": "insurance",
      "5": "green",
      "6": "Ashberry",
      "7": "W23K594 / w23k594",
      "8": "0879580662 / 0879 580 662 / 0879-580-662",
      "9": "joint",
      "10": "rent",
      "11": "B",
      "12": "B",
      "13": "C",
      "14": "B",
      "15": "A",
      "16": "G",
      "17": "B",
      "18": "A",
      "19": "D",
      "20": "E",
      "21": "A / B",
      "22": "A / B",
      "23": "C / D",
      "24": "C / D",
      "25": "A / D",
      "26": "A / D",
      "27": "C",
      "28": "D",
      "29": "A",
      "30": "E",
      "31": "fossils ",
      "32": "disease ",
      "33": "cup ",
      "34": "animals",
      "35": "flowers ",
      "36": "brighter",
      "37": "recycling",
      "38": "libraries ",
      "39": "tram",
      "40": "grass"
    },
    "reading": {
      "1": "B",
      "2": "C",
      "3": "H",
      "4": "G",
      "5": "E",
      "6": "D",
      "7": "F",
      "8": "A",
      "9": "apples / apple",
      "10": "fructose",
      "11": "palate",
      "12": "brushing ",
      "13": "labels ",
      "14": "True",
      "15": "Not given / Not Given",
      "16": "False",
      "17": "False",
      "18": "D",
      "19": "B",
      "20": "E",
      "21": "C",
      "22": "F",
      "23": "H",
      "24": "C",
      "25": "E",
      "26": "G",
      "27": "B",
      "28": "x",
      "29": "vi",
      "30": "vii",
      "31": "viii",
      "32": "ix",
      "33": "i",
      "34": "iv",
      "35": "thought experiment / thought-experiment",
      "36": "parallel track",
      "37": "C",
      "38": "A",
      "39": "B",
      "40": "C"
    }
  },
  "ielts15": {
    "listening": {
      "1": "receptionist",
      "2": "Medical",
      "3": "Chastons",
      "4": "appointments",
      "5": "database",
      "6": "experience",
      "7": "confident",
      "8": "temporary",
      "9": "1.15 / 1:15 / 01:15 / one fifteen",
      "10": "parking",
      "11": "B",
      "12": "A",
      "13": "A",
      "14": "C",
      "15": "F",
      "16": "G",
      "17": "E",
      "18": "A",
      "19": "C",
      "20": "B",
      "21": "B / D",
      "22": "B / D",
      "23": "D",
      "24": "A",
      "25": "C",
      "26": "G",
      "27": "F",
      "28": "A",
      "29": "B",
      "30": "C",
      "31": "plot",
      "32": "poverty",
      "33": "Europe",
      "34": "poetry",
      "35": "drawings",
      "36": "furniture",
      "37": "lamps",
      "38": "harbour / harbor",
      "39": "children",
      "40": "relatives"
    },
    "reading": {
      "1": "D",
      "2": "C",
      "3": "E",
      "4": "B",
      "5": "D",
      "6": "energy",
      "7": "food",
      "8": "gardening",
      "9": "obesity",
      "10": "C / D",
      "11": "C / D",
      "12": "A / D",
      "13": "A / D",
      "14": "B",
      "15": "C",
      "16": "D",
      "17": "C",
      "18": "B",
      "19": "A",
      "20": "E",
      "21": "B",
      "22": "D",
      "23": "Yes",
      "24": "No",
      "25": "Not given / Not Given",
      "26": "Yes",
      "27": "Yes",
      "28": "Not given / Not Given",
      "29": "No",
      "30": "No",
      "31": "I",
      "32": "F",
      "33": "A",
      "34": "C",
      "35": "H",
      "36": "E",
      "37": "B",
      "38": "A",
      "39": "D",
      "40": "C"
    }
  },
  "ielts16": {
    "listening": {
      "1": "5th July / 5 July / July 5/ July 5th",
      "2": "Dublin",
      "3": "323682",
      "4": "07780367021",
      "5": "BN12SE",
      "6": "jacket",
      "7": "21st July / 21 July / July 21 / July 21st",
      "8": "cafe",
      "9": "bus",
      "10": "135970",
      "11": "B",
      "12": "C",
      "13": "C",
      "14": "A",
      "15": "C",
      "16": "D",
      "17": "F",
      "18": "H",
      "19": "C",
      "20": "A",
      "21": "C",
      "22": "A",
      "23": "A",
      "24": "A",
      "25": "F",
      "26": "C",
      "27": "G",
      "28": "H",
      "29": "B",
      "30": "A",
      "31": "ships",
      "32": "water",
      "33": "vinegar",
      "34": "pots",
      "35": "secret",
      "36": "pine",
      "37": "oil",
      "38": "copy",
      "39": "smoke",
      "40": "noise"
    },
    "reading": {
      "1": "Not given",
      "2": "True",
      "3": "True",
      "4": "False",
      "5": "False",
      "6": "pivot / platform",
      "7": "parapet",
      "8": "quarters",
      "9": "ammunition",
      "10": "B",
      "11": "E",
      "12": "D",
      "13": "A",
      "14": "C",
      "15": "C",
      "16": "A",
      "17": "E",
      "18": "B",
      "19": "F",
      "20": "H",
      "21": "K",
      "22": "A",
      "23": "G",
      "24": "D",
      "25": "J",
      "26": "capsaicin",
      "27": "immunity-boosting",
      "28": "B",
      "29": "F",
      "30": "E",
      "31": "F",
      "32": "C",
      "33": "D",
      "34": "E",
      "35": "A",
      "36": "G",
      "37": "H",
      "38": "True",
      "39": "False",
      "40": "Not given"
    }
  },
  "ielts17": {
    "listening": {
      "1": "Connor",
      "2": "28th June / 28 June / June 28 / June 28th",
      "3": "8 / eight",
      "4": "twin",
      "5": "family",
      "6": "terrace",
      "7": "39",
      "8": "wheelchair",
      "9": "fish",
      "10": "079057738795",
      "11": "C/D",
      "12": "C/D",
      "13": "A/B",
      "14": "A/B",
      "15": "D",
      "16": "C",
      "17": "B",
      "18": "A",
      "19": "D",
      "20": "B",
      "21": "B",
      "22": "B",
      "23": "B",
      "24": "A",
      "25": "C",
      "26": "C",
      "27": "H",
      "28": "E",
      "29": "G",
      "30": "I",
      "31": "rocks",
      "32": "motion",
      "33": "temperature",
      "34": "satellites",
      "35": "conditions",
      "36": "chemical",
      "37": "exclusion",
      "38": "blocked",
      "39": "dangers",
      "40": "provisions"
    },
    "reading": {
      "1": "B",
      "2": "D",
      "3": "C",
      "4": "A",
      "5": "D",
      "6": "E",
      "7": "ambient temperature",
      "8": "(two) wires / 2 wires",
      "9": "(the) thermostat",
      "10": "(smart phone) apps",
      "11": "screwdriver",
      "12": "in use/occupied",
      "13": "efficiency",
      "14": "1.1 billion years",
      "15": "butterwort",
      "16": "Skye Bridge",
      "17": "True",
      "18": "False",
      "19": "Not given",
      "20": "True",
      "21": "climatic conditions",
      "22": "rainfall",
      "23": "otters and mink",
      "24": "(Atlantic) storms / (Atlantic) storm",
      "25": "(vast) kelp forests/kelp",
      "26": "(windy) open waters",
      "27": "films",
      "28": "E",
      "29": "C",
      "30": "A",
      "31": "F",
      "32": "C/D",
      "33": "C/D",
      "34": "B/D",
      "35": "B/D",
      "36": "SM",
      "37": "DB",
      "38": "EMS",
      "39": "HB",
      "40": "EY"
    }
  }
};
