export const OBJECTIVE_ANSWER_KEYS = {
  "ielts1": {
    "listening": {
      "1": "9.30 (am) / 9:30 (am) / 9 30 (am) / 9.30 (AM) / 9:30 (AM) / 9 30 (AM)",
      "2": "Helendale",
      "3": "Central Street/ Central St",
      "4": "(number/no./#) 792",
      "5": "8.55 (am) / 8:55 (am) / 8.55 (AM) / 8:55 (AM)",
      "6": "1.80",
      "7": "7.30/7:30",
      "8": "7.15",
      "9": "commuter",
      "10": "afternoon",
      "11": "c",
      "12": "c",
      "13": "a",
      "14": "b",
      "15": "first year/1st year/ First year",
      "16": "(right) balance",
      "17": "international/foreign (students)",
      "18": "relaxation/Relaxation",
      "19": "motivation/Motivation",
      "20": "research/advanced/Research/Advanced",
      "21": "The Secret Garden",
      "22": "(the) 20th century/twentieth century",
      "23": "walk",
      "24": "motivations/motivation",
      "25": "abstract ideas",
      "26": "roses",
      "27": "dark to light / darkness to lightness",
      "28": "health/Health",
      "29": "environment/Environment",
      "30": "human companionship",
      "31": "negative/Negative",
      "32": "pleasure",
      "33": "poverty",
      "34": "active/Active",
      "35": "success",
      "36": "b",
      "37": "a",
      "38": "c",
      "39": "a",
      "40": "b"
    },
    "reading": {
      "1": "vi",
      "2": "viii",
      "3": "vii",
      "4": "i",
      "5": "ii",
      "6": "iv",
      "7": "Royal Society / royal society",
      "8": "(his) niece / His niece / Niece",
      "9": "telescope",
      "10": "optics",
      "11": "particles",
      "12": "motion",
      "13": "calculus",
      "14": "remote",
      "15": "native population",
      "16": "single",
      "17": "Ice shelves / ice shelves",
      "18": "NOT GIVEN",
      "19": "FALSE",
      "20": "TRUE",
      "21": "FALSE",
      "22": "E",
      "23": "C",
      "24": "A",
      "25": "G",
      "26": "D",
      "27": "D",
      "28": "B",
      "29": "A",
      "30": "B",
      "31": "B",
      "32": "NOT GIVEN",
      "33": "TRUE",
      "34": "NO",
      "35": "NOT GIVEN",
      "36": "NO",
      "37": "D",
      "38": "C",
      "39": "A",
      "40": "B"
    }
  },
  "ielts2": {
    "listening": {
      "1": "Lynda",
      "2": "Unit 15 / Unit fifteen",
      "3": "5577",
      "4": "night shift",
      "5": "swipe card",
      "6": "September 1975 / Sept 1975",
      "7": "A / C",
      "8": "A / C",
      "9": "Fifteen dollars / fifteen dollars / $15 / 15 dollars",
      "10": "60 minutes/sixty minutes/one hour/1 hour",
      "11": "B",
      "12": "A",
      "13": "A",
      "14": "B",
      "15": "C",
      "16": "2 July/2nd July",
      "17": "9:15 AM/9:15 am/9.15/9:15/nine fifteen AM/nine fifteen am/9:15 A.M./9:15 a.m./9.15/9:15/nine fifteen A.M./nine fifteen a.m.",
      "18": "president",
      "19": "Observation hut / observation hut",
      "20": "2 PM/2 pm/two pm/2 p.m/ 2 P.M.",
      "21": "safety procedures / directions / safety rules",
      "22": "eye protection / safety glasses / goggles",
      "23": "clean-up / clean up / cleanup",
      "24": "naked flame",
      "25": "leather",
      "26": "C",
      "27": "B",
      "28": "C",
      "29": "C/E",
      "30": "C/E",
      "31": "fuel",
      "32": "Combustion engine / combustion engine",
      "33": "145% / 145 per cent",
      "34": "agriculture",
      "35": "(a) barrier",
      "36": "46 million",
      "37": "118 million",
      "38": "vegetation zones",
      "39": "(certain) disease(s)",
      "40": "species composition"
    },
    "reading": {
      "1": "viii",
      "2": "iii",
      "3": "vii",
      "4": "i",
      "5": "vi",
      "6": "ix",
      "7": "ii",
      "8": "Cauliflower rosettes / cauliflower rosettes",
      "9": "Periodic unsettling / periodic unsettling",
      "10": "Milk sugars / milk sugars",
      "11": "Liquefied yogurt / liquefied yogurt",
      "12": "C/E",
      "13": "C/E",
      "14": "vi",
      "15": "ix",
      "16": "v",
      "17": "iv",
      "18": "x",
      "19": "ii",
      "20": "vii",
      "21": "iii",
      "22": "energy",
      "23": "subsistence needs",
      "24": "rural/impoverished",
      "25": "pesticide use",
      "26": "protein deficiency",
      "27": "D",
      "28": "E",
      "29": "A",
      "30": "C",
      "31": "B",
      "32": "E",
      "33": "B",
      "34": "F",
      "35": "YES",
      "36": "YES",
      "37": "YES",
      "38": "NO",
      "39": "NOT GIVEN",
      "40": "NO"
    }
  },
  "ielts3": {
    "listening": {
      "1": "documents",
      "2": "keyboard",
      "3": "flowers",
      "4": "tools",
      "5": "Saturday",
      "6": "Maired",
      "7": "bridge",
      "8": "May 14 / 14 May",
      "9": "park",
      "10": "newspaper",
      "11": "C",
      "12": "B",
      "13": "A",
      "14": "H",
      "15": "G",
      "16": "films",
      "17": "reports",
      "18": "region",
      "19": "job",
      "20": "housing",
      "21": "E",
      "22": "I",
      "23": "C",
      "24": "G",
      "25": "B",
      "26": "D",
      "27": "A",
      "28": "aims / goals",
      "29": "staff",
      "30": "feedback",
      "31": "hook",
      "32": "string",
      "33": "danger",
      "34": "rubber",
      "35": "light",
      "36": "intelligence",
      "37": "tails",
      "38": "energy",
      "39": "chemical",
      "40": "diet"
    },
    "reading": {
      "1": "seafaring",
      "2": "merchant",
      "3": "temple",
      "4": "craftsmen",
      "5": "timber / wood",
      "6": "partnership",
      "7": "ivory",
      "8": "commission",
      "9": "TRUE",
      "10": "FALSE",
      "11": "TRUE",
      "12": "TRUE",
      "13": "not given",
      "14": "iv",
      "15": "ii",
      "16": "vii",
      "17": "i",
      "18": "v",
      "19": "vi",
      "20": "FALSE",
      "21": "TRUE",
      "22": "not given",
      "23": "TRUE",
      "24": "vertical integration",
      "25": "movie moguls",
      "26": "divestiture",
      "27": "D",
      "28": "C",
      "29": "E",
      "30": "B",
      "31": "environmental",
      "32": "light",
      "33": "multi-tasking / multitasking",
      "34": "food",
      "35": "predator",
      "36": "E",
      "37": "H",
      "38": "B",
      "39": "B",
      "40": "A"
    }
  },
  "ielts4": {
    "listening": {
      "1": "unfriendly",
      "2": "noisy",
      "3": "23.50 / 23:50",
      "4": "insects",
      "5": "bathrooms",
      "6": "party",
      "7": "Shadforth / shadforth",
      "8": "towel",
      "9": "breakfast",
      "10": "kitchen",
      "11": "B",
      "12": "A",
      "13": "C",
      "14": "B",
      "15": "A",
      "16": "A",
      "17": "E",
      "18": "C",
      "19": "F",
      "20": "A",
      "21": "A",
      "22": "B",
      "23": "A",
      "24": "B",
      "25": "A",
      "26": "A",
      "27": "background",
      "28": "theory",
      "29": "costs",
      "30": "time",
      "31": "religions",
      "32": "nature",
      "33": "flight",
      "34": "stars",
      "35": "practical",
      "36": "education",
      "37": "king",
      "38": "entertainment",
      "39": "opera",
      "40": "electricity"
    },
    "reading": {
      "1": "TRUE",
      "2": "FALSE",
      "3": "not given",
      "4": "not given",
      "5": "TRUE",
      "6": "FALSE",
      "7": "TRUE",
      "8": "D",
      "9": "B",
      "10": "G",
      "11": "C",
      "12": "E",
      "13": "F",
      "14": "hairs",
      "15": "charge / electric charge",
      "16": "pores",
      "17": "water",
      "18": "concave",
      "19": "E",
      "20": "D",
      "21": "B",
      "22": "C",
      "23": "E",
      "24": "I",
      "25": "F",
      "26": "H",
      "27": "i",
      "28": "x",
      "29": "ii",
      "30": "vii",
      "31": "iii",
      "32": "v",
      "33": "F",
      "34": "E",
      "35": "C",
      "36": "D",
      "37": "B",
      "38": "E",
      "39": "A",
      "40": "E"
    }
  },
  "ielts5": {
    "listening": {
      "1": "2086132978",
      "2": "visiontech",
      "3": "doctor",
      "4": "garage",
      "5": "furniture",
      "6": "fridge",
      "7": "school",
      "8": "950",
      "9": "quiet",
      "10": "friend",
      "11": "contact details",
      "12": "emergency",
      "13": "radio",
      "14": "extra keys / (extra) keys / spare keys",
      "15": "window locks / (window) locks",
      "16": "C",
      "17": "D",
      "18": "F",
      "19": "G",
      "20": "E",
      "21": "B",
      "22": "C",
      "23": "B",
      "24": "A",
      "25": "C",
      "26": "C",
      "27": "global hunger / hunger",
      "28": "pollution",
      "29": "wood",
      "30": "grass",
      "31": "marketing",
      "32": "interests",
      "33": "jobs",
      "34": "health",
      "35": "C",
      "36": "E",
      "37": "A",
      "38": "D",
      "39": "A",
      "40": "C"
    },
    "reading": {
      "1": "v / vi",
      "2": "viii / vii",
      "3": "i",
      "4": "vi / iv",
      "5": "iv / viii",
      "6": "ii",
      "7": "national development / science",
      "8": "economy",
      "9": "guidelines",
      "10": "memorisation / language",
      "11": "equipment",
      "12": "masters degree / master's degree",
      "13": "respect / status / social respect",
      "14": "ii / viii",
      "15": "iv / iii",
      "16": "vi / vii",
      "17": "iii / iv",
      "18": "vii / vi",
      "19": "viii / ix",
      "20": "i / ii",
      "21": "cauliflower rosettes",
      "22": "fermentation process / periodic unsettling",
      "23": "milk sugars",
      "24": "liquified yogurt / liquefied yogurt / yogurt",
      "25": "B / C",
      "26": "E",
      "27": "D",
      "28": "B",
      "29": "A",
      "30": "C",
      "31": "B",
      "32": "D / C",
      "33": "E / D",
      "34": "A",
      "35": "workplace / workplaces",
      "36": "conversations / acquaintances",
      "37": "behaviour / conversations",
      "38": "behaviour / internet",
      "39": "waste / cities",
      "40": "A"
    }
  },
  "ielts6": {
    "listening": {
      "1": "white",
      "2": "office",
      "3": "camera",
      "4": "umbrella",
      "5": "13 May / May 13 / May 13th",
      "6": "airport",
      "7": "taxi",
      "8": "Docherty",
      "9": "river",
      "10": "7979605437",
      "11": "G",
      "12": "D",
      "13": "A",
      "14": "E",
      "15": "C",
      "16": "B",
      "17": "A",
      "18": "C",
      "19": "C",
      "20": "A",
      "21": "B",
      "22": "A",
      "23": "A",
      "24": "C",
      "25": "B",
      "26": "E",
      "27": "B",
      "28": "G",
      "29": "A",
      "30": "F",
      "31": "migration",
      "32": "eyes",
      "33": "lizard",
      "34": "trade",
      "35": "survival",
      "36": "political",
      "37": "ships",
      "38": "horses",
      "39": "industry",
      "40": "tourism"
    },
    "reading": {
      "1": "vi",
      "2": "x",
      "3": "iii",
      "4": "ix",
      "5": "iv",
      "6": "i",
      "7": "vii",
      "8": "North America",
      "9": "super hot fires / hot fires / fires",
      "10": "stored carbon / (stored) carbon",
      "11": "winds",
      "12": "drought",
      "13": "beetle",
      "14": "skin samples / skin (samples)",
      "15": "noise pollution / noise (pollution)",
      "16": "around Tasmania / (around) Tasmania",
      "17": "sperm whales / sperm (whales)",
      "18": "sound waves",
      "19": "nutrients",
      "20": "microbubbles",
      "21": "blood",
      "22": "not given",
      "23": "TRUE",
      "24": "not given",
      "25": "TRUE",
      "26": "FALSE",
      "27": "B",
      "28": "A",
      "29": "B",
      "30": "D",
      "31": "C",
      "32": "D",
      "33": "B",
      "34": "C",
      "35": "A",
      "36": "H",
      "37": "D",
      "38": "F",
      "39": "G",
      "40": "B"
    }
  },
  "ielts7": {
    "listening": {
      "1": "7.30 / 7:30",
      "2": "pencils",
      "3": "top",
      "4": "August",
      "5": "instructions",
      "6": "55",
      "7": "beginners",
      "8": "Kahui / kahui",
      "9": "battery",
      "10": "show",
      "11": "B",
      "12": "E",
      "13": "B",
      "14": "C",
      "15": "G",
      "16": "I",
      "17": "B",
      "18": "E",
      "19": "C",
      "20": "A",
      "21": "C",
      "22": "A",
      "23": "B",
      "24": "C",
      "25": "A",
      "26": "G",
      "27": "A",
      "28": "D",
      "29": "C",
      "30": "E",
      "31": "food",
      "32": "hero",
      "33": "feathers",
      "34": "shells",
      "35": "diamond",
      "36": "shark",
      "37": "teeth",
      "38": "messages",
      "39": "meeting",
      "40": "escape"
    },
    "reading": {
      "1": "FALSE",
      "2": "not given",
      "3": "TRUE",
      "4": "TRUE",
      "5": "not given",
      "6": "FALSE",
      "7": "not given",
      "8": "not given",
      "9": "A",
      "10": "B",
      "11": "C",
      "12": "C",
      "13": "A",
      "14": "not given",
      "15": "TRUE",
      "16": "FALSE",
      "17": "not given",
      "18": "fertilizer / fertiliser",
      "19": "lasers",
      "20": "cereals",
      "21": "communication",
      "22": "C",
      "23": "F",
      "24": "H",
      "25": "A",
      "26": "D",
      "27": "E",
      "28": "D",
      "29": "C",
      "30": "E",
      "31": "A",
      "32": "B",
      "33": "C",
      "34": "D",
      "35": "B",
      "36": "C",
      "37": "generation",
      "38": "citizen",
      "39": "abstract",
      "40": "music"
    }
  },
  "ielts8": {
    "listening": {
      "1": "C",
      "2": "C",
      "3": "C",
      "4": "13th November / 13 November / November 13 / 13th of November",
      "5": "8 / 8.00 / 8:00 / 8 am / 8.00 am / 8:00 am",
      "6": "15 / fifteen",
      "7": "3.25",
      "8": "dairy-free / dairy free",
      "9": "Beecham / beecham",
      "10": "523",
      "11": "direct sunlight",
      "12": "usage / energy usage",
      "13": "cool shower",
      "14": "cooling points",
      "15": "sweating",
      "16": "11 to 3 / 11 a.m. to 3 p.m. / eleven to three",
      "17": "umbrella / an umbrella",
      "18": "cotton or linen",
      "19": "physical exercise",
      "20": "health issues",
      "21": "C",
      "22": "C",
      "23": "B",
      "24": "A",
      "25": "C",
      "26": "well constructed",
      "27": "relevant",
      "28": "typing mistakes",
      "29": "sentence structures",
      "30": "punctuation",
      "31": "B",
      "32": "C",
      "33": "A",
      "34": "C",
      "35": "B",
      "36": "A",
      "37": "C",
      "38": "winter months",
      "39": "positive attitude",
      "40": "motivated"
    },
    "reading": {
      "1": "C",
      "2": "F",
      "3": "I",
      "4": "B",
      "5": "G",
      "6": "action",
      "7": "angle",
      "8": "re-form / reform",
      "9": "undermined",
      "10": "crashing",
      "11": "absorbing",
      "12": "lifespan",
      "13": "D",
      "14": "B",
      "15": "hierarchy",
      "16": "emerge",
      "17": "cooperation",
      "18": "norms",
      "19": "performance",
      "20": "B",
      "21": "E",
      "22": "D",
      "23": "E",
      "24": "NOT GIVEN",
      "25": "TRUE",
      "26": "FALSE",
      "27": "NOT GIVEN",
      "28": "TRUE",
      "29": "TRUE",
      "30": "confusion",
      "31": "patterns",
      "32": "interpret",
      "33": "A",
      "34": "B",
      "35": "B",
      "36": "C",
      "37": "basis",
      "38": "fine-tunes / fine tunes",
      "39": "deletes",
      "40": "curation"
    }
  }
  ,"ielts9": {
    "listening": {
      "1": "Marrowfield",
      "2": "relative",
      "3": "socialize / socialise",
      "4": "full",
      "5": "domestic life",
      "6": "clouds",
      "7": "timing",
      "8": "animal magic",
      "9": "movement / animal movement",
      "10": "dark",
      "11": "B / C",
      "12": "B / C",
      "13": "B / D",
      "14": "B / D",
      "15": "C",
      "16": "B",
      "17": "B",
      "18": "C",
      "19": "A",
      "20": "A",
      "21": "A / E",
      "22": "A / E",
      "23": "B / D",
      "24": "B / D",
      "25": "G",
      "26": "E",
      "27": "B",
      "28": "C",
      "29": "F",
      "30": "A",
      "31": "technical",
      "32": "cheap",
      "33": "thousands",
      "34": "identification",
      "35": "tracking",
      "36": "military",
      "37": "location",
      "38": "prediction",
      "39": "database",
      "40": "trust"
    },
    "reading": {
      "1": "G",
      "2": "D",
      "3": "C",
      "4": "F",
      "5": "architects",
      "6": "moisture",
      "7": "layers",
      "8": "speed",
      "9": "C",
      "10": "A",
      "11": "B",
      "12": "D",
      "13": "A",
      "14": "iii",
      "15": "viii",
      "16": "vi",
      "17": "v",
      "18": "vii",
      "19": "i",
      "20": "iv",
      "21": "A",
      "22": "C",
      "23": "B",
      "24": "speed",
      "25": "50 / fifty",
      "26": "strict",
      "27": "B",
      "28": "A",
      "29": "C",
      "30": "C",
      "31": "H",
      "32": "D",
      "33": "F",
      "34": "E",
      "35": "B",
      "36": "NO",
      "37": "NOT GIVEN",
      "38": "YES",
      "39": "NO",
      "40": "NOT GIVEN"
    }
  }
  ,"ielts10": {
        "listening": {
      "1": "port",
      "2": "13th September / thirteenth September / 13 September",
      "3": "1100 / 1,100",
      "4": "Beatrice",
      "5": "07740922166",
      "6": "b.russell64@xmail.co.uk",
      "7": "garden",
      "8": "1000 / 1,000",
      "9": "center / centre",
      "10": "parking",
      "11": "C",
      "12": "B",
      "13": "A",
      "14": "C",
      "15": "A",
      "16": "C",
      "17": "B",
      "18": "A",
      "19": "C",
      "20": "B",
      "21": "B/C",
      "22": "B/C",
      "23": "A/E",
      "24": "A/E",
      "25": "C/D",
      "26": "C/D",
      "27": "E",
      "28": "B",
      "29": "A",
      "30": "C",
      "31": "corporate",
      "32": "exploit",
      "33": "staff",
      "34": "shock",
      "35": "laws",
      "36": "year",
      "37": "marketing",
      "38": "charities",
      "39": "cheap",
      "40": "relevant"
    },
    "reading": {
      "1": "iii",
      "2": "i",
      "3": "vi",
      "4": "viii",
      "5": "v",
      "6": "2006",
      "7": "butterflies",
      "8": "hibernation",
      "9": "extinctions",
      "10": "TRUE",
      "11": "NOT GIVEN",
      "12": "FALSE",
      "13": "NOT GIVEN",
      "14": "C",
      "15": "E",
      "16": "F",
      "17": "B",
      "18": "C",
      "19": "G",
      "20": "CT",
      "21": "PA",
      "22": "OH",
      "23": "SP",
      "24": "HF",
      "25": "OH",
      "26": "D",
      "27": "giant clams / clams",
      "28": "ten months",
      "29": "marble and bronze",
      "30": "wooden casing",
      "31": "inscriptions",
      "32": "mechanical clock / clock",
      "33": "C",
      "34": "H",
      "35": "F",
      "36": "G",
      "37": "B",
      "38": "C",
      "39": "C",
      "40": "A"
    }
  }

  ,"ielts11": {
  "listening": {
    "1": "48",
    "2": "R16 GH7",
    "3": "07754",
    "4": "PA 365",
    "5": "E6",
    "6": "B / D / E",
    "7": "B / D / E",
    "8": "B / D / E",
    "9": "C",
    "10": "C",
    "11": "C",
    "12": "B",
    "13": "A",
    "14": "F",
    "15": "A / C",
    "16": "A / C",
    "17": "C / E",
    "18": "C / E",
    "19": "B / C",
    "20": "B / C",
    "21": "A",
    "22": "C",
    "23": "A",
    "24": "B",
    "25": "B",
    "26": "ten / 10",
    "27": "Africa / Asia / Africa-Asia / Asia-Africa",
    "28": "1000 words / 1,000 words",
    "29": "30th of October / 30 October / October 30 / 30th October",
    "30": "B",
    "31": "C",
    "32": "B",
    "33": "B",
    "34": "B",
    "35": "very calm seas",
    "36": "larger slicks",
    "37": "toxic waste",
    "38": "eco-friendly / eco friendly",
    "39": "discernible drawbacks",
    "40": "deadline for submission"
  },
  "reading": {
    "1": "viii",
    "2": "i",
    "3": "ix",
    "4": "vii",
    "5": "v",
    "6": "iii",
    "7": "NO",
    "8": "YES",
    "9": "NOT GIVEN",
    "10": "NOT GIVEN",
    "11": "YES",
    "12": "NOT GIVEN",
    "13": "NO",
    "14": "YES",
    "15": "C",
    "16": "F",
    "17": "H",
    "18": "G",
    "19": "B",
    "20": "D",
    "21": "D",
    "22": "B",
    "23": "C",
    "24": "A",
    "25": "NOT GIVEN",
    "26": "TRUE",
    "27": "TRUE",
    "28": "AP",
    "29": "RH",
    "30": "PJ",
    "31": "BB",
    "32": "TB",
    "33": "SB",
    "34": "PJ",
    "35": "PL",
    "36": "FALSE",
    "37": "TRUE",
    "38": "TRUE",
    "39": "TRUE",
    "40": "NOT GIVEN"
  }
}

};
